

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO


security:
  oauth2:
    client:
      petapiintegration:
        client-id: 1IliKmJJLC04JXFeY7v0C1FLBsup6HLObhPwCclkkPB9ZtAQff
        clientSecret: 8b0lDLqQoUI2ISMDBYRjGluLN9KFu8UQwl4XxJtH
        grant-type: client_credentials
        access-token-uri: https://api.petfinder.com/v2/oauth2/token



messages:
  base-uri: https://api.petfinder.com/v2/animals?location=Andover, MA&distance=2

